apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-dogs-api
  labels:
    app: cats-dogs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-dogs-api
  template:
    metadata:
      labels:
        app: cats-dogs-api
    spec:
      containers:
        - name: cats-dogs-api
          image: ghcr.io/basavarajurevannakumar/cats-dogs-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
